sudo: false
language: node_js
node_js:
  - '8'
  - '9'
cache:
  directories:
    - ~/.npm
notifications:
  email: false
deploy:
  script: scripts/deploy.sh
  provider: script
  skip_cleanup: true
  on:
    branch: master
